export const mcqQuestions = [
  { q: "1. Success in business mainly depends on:", options: ["Contacts", "Government", "Hard Work", "Luck", "None"] },
  { q: "2. Profit in business is:", options: ["Necessary", "Bad", "Optional", "Irrelevant", "Unethical"] },
  { q: "3. Innovation is:", options: ["Waste", "Risky", "Unneeded", "Important", "Optional"] },
  { q: "4. Time management means:", options: ["Ignoring time", "Delaying", "Random work", "Sleeping", "Planning work"] },
  { q: "5. Failure should be:", options: ["Avoided", "Ignored", "Feared", "Learned from", "Hidden"] },
  { q: "6. Business growth depends on:", options: ["Luck", "Chance", "Others", "Effort", "None"] },
  { q: "7. Decision making should be:", options: ["Delayed", "Avoided", "Random", "Emotional", "Quick & smart"] },
  { q: "8. Risk in business is:", options: ["Bad", "Avoidable", "Necessary", "Optional", "Useless"] },
  { q: "9. Entrepreneurs should:", options: ["Wait", "Delay", "Follow", "Act", "Ignore"] },
  { q: "10. Competition means:", options: ["Fear", "Loss", "Problem", "Growth", "None"] },
  { q: "11. Success requires:", options: ["Luck", "Avoidance", "Waiting", "Planning", "None"] }
];

export const pairedQuestions = [
  { q: "1.", A: "Work has to be done, so I try to do it better.", B: "I keep good company to get my work done." },
  { q: "2.", A: "I feel happier when responsibility increases.", B: "I settle first then act." },
  { q: "3.", A: "Avoid losses always.", B: "Understanding earning is first step." },
  { q: "4.", A: "Avoid risk of failure.", B: "Maintain people's trust." },
  { q: "5.", A: "Strive to progress.", B: "Do what feels secure." },
  { q: "6.", A: "People ridicule failure.", B: "Take advice when needed." },
  { q: "7.", A: "Solve problems actively.", B: "Stick to current work." },
  { q: "8.", A: "Trust own thoughts.", B: "I can do better." },
  { q: "9.", A: "Maintain relationships.", B: "Learn from experience." },
  { q: "10.", A: "Learn from failure.", B: "Prefer comfort." },
  { q: "11.", A: "Depend on luck.", B: "Find reasons of failure." },
  { q: "12.", A: "Employees are friends.", B: "Switch for better work." },
  { q: "13.", A: "Think before action.", B: "Sacrifice for others." },
  { q: "14.", A: "Need capital first.", B: "Take own decisions." },
  { q: "15.", A: "Maintain trust.", B: "Find alternatives." },
  { q: "16.", A: "Avoid mistakes.", B: "Enjoy socializing." },
  { q: "17.", A: "Keep money safe.", B: "Trust own work." },
  { q: "18.", A: "Want comfort money.", B: "Need help in decisions." },
  { q: "19.", A: "Support relatives.", B: "Enjoy solving problems." },
  { q: "20.", A: "Avoid hurting others.", B: "Money is key." },
  { q: "21.", A: "Grow fast.", B: "Avoid blame." },
  { q: "22.", A: "Act independently.", B: "Money = happiness." },
  { q: "23.", A: "Blame others.", B: "Do what feels right." },
  { q: "24.", A: "Protect reputation.", B: "Want luxury." },
  { q: "25.", A: "Comfortable house.", B: "Learn from failure." },
  { q: "26.", A: "Think long-term.", B: "Control everything." },
  { q: "27.", A: "Money is main goal.", B: "Enjoy social work." },
  { q: "28.", A: "Ignore criticism.", B: "Feel bad on failure." },
  { q: "29.", A: "Avoid difficulties.", B: "Take advice." },
  { q: "30.", A: "Learn from experience.", B: "Want money." },
  { q: "31.", A: "Prefer easy life.", B: "Analyze failure." },
  { q: "32.", A: "Avoid interference.", B: "Do anything for money." }
];
